Description: >
  Michael Olatunji / Udagram, 
  Udacity Cloud DevOps Nanodegree Project 2
  Cloudformation Infrastructure as Code
  The compute hardware (servers)
  
Parameters:
  EnvironmentName:
    Description: An Environment name that will prefixed to resources names
    Type: String

Resources:
  UdagramRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      Description: Creates an IAM Role for Udagram with read-only access to S3 bucket
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      
  UdagramRolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: 'arn:aws:s3:::udagram-imyke/*'
      Roles: 
        - !Ref UdagramRole

  UdagramInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref UdagramRole

Outputs:
  PolicyId:
    Description: The logical ID of the IAM policy
    Value: !Ref UdagramRolePolicies
    Export:
      Name: !sub ${EnvironmentName}-IAM-POLICY
