Description: >
  Udagram, Udacity Cloud DevOps Nanodegree Project 2: CloudFormation
  by Michael Olatunji

Parameters:
  EnvironmentName:
    Description: An Environment name that will prefixed to resources
    Type: String
  VpcCIDR:
    Description: IP range CIDR for this resource
    Type: String

Resources:

  VPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags: 
        - Key: Name 
          Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
          
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      
Outputs: